# Generated by Django 4.2 on 2025-07-22 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('is_contracted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
