# Generated by Django 4.2 on 2025-07-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_consulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulation',
            old_name='is_contracted',
            new_name='is_contacted',
        ),
    ]
