# Generated by Django 4.2 on 2025-07-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_rename_follo_up_consultation_price_doctor_follow_up_consultation_price'),
        ('shared', '0003_rename_is_contracted_consulation_is_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.doctor'),
        ),
    ]
