# Generated by Django 4.2 on 2025-06-11 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinictCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('working_days', models.CharField(max_length=250)),
                ('working_hours', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/clinics/clinic/image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='clinics.clinictcategory')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='shared.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
