# Generated by Django 4.2 on 2025-06-11 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='apps/doctors/doctor/photo/')),
                ('specialties', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('initial_consultation_price', models.PositiveBigIntegerField(default=0)),
                ('follo_up_consultation_price', models.PositiveBigIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.doctorcategory')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
