# Generated by Django 4.2 on 2025-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
