# Generated by Django 4.2 on 2025-06-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='follo_up_consultation_price',
            new_name='follow_up_consultation_price',
        ),
    ]
